spring.application.name=tech-academy-springboot

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show_sql=true
spring.jpa.format_sql=true

# expose specific endpoints
# management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers

# or expose everything (careful in production)
management.endpoints.web.exposure.include=*

# custom port (good practice — keeps actuator off the main port)
management.server.port=8081

# show full health details
management.endpoint.health.show-details=always